
//vai falhar e gerar VariableNotFoundException
fun teste() {
    x
}

//vai falhar e gerar VariableNotFoundException
fun teste() {
    x = 10
}
